export const CUSTOMIZATION_CONFIG = {
  options: {
    title: "Options",
    settings: [
      {
        codename: "reset_customization",
        name: "Reset Customization",
        description: "Reset all customization settings to default",
        emoji: "refresh",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "import_export",
        name: "Import/Export",
        description: "Import or export customization settings",
        emoji: "import-export",
        type: "action",
        defaultValue: null,
      },
    ],
  },
  themes: {
    title: "Themes",
    settings: [
      {
        codename: "amoled_theme",
        name: "AMOLED Theme",
        description: "A neat black theme for OLED screens",
        emoji: "brush",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "white_mode",
        name: "White Mode",
        description: "A light theme for better visibility in sunlight",
        emoji: "brush",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "gray_theme",
        name: "Dark Theme",
        description: "A gray theme for a neutral look",
        emoji: "brush",
        type: "action",
        defaultValue: null,
      },
    ],
  },
  colors: {
    title: "Colors",
    settings: [
      {
        codename: "wallpaper_accent",
        name: "Use wallpaper accent color",
        description: "Change the coloring based on the wallpaper colors",
        emoji: "",
        type: "toggle",
        defaultValue: null,
      },
      {
        codename: "album_cover_accent",
        name: "Use album cover as accent color",
        description: "Change the coloring based on the album cover colors",
        emoji: "",
        type: "toggle",
        defaultValue: null,
      },
      {
        codename: "primary_color",
        name: "Primary Color",
        description: "Set the accent color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "secondary_color",
        name: "Secondary Color",
        description: "Set the secondary color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "background_color",
        name: "Background Color",
        description: "Set the background color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
  views: {
    title: "App Style",
    settings: [
      {
        codename: "nav_style",
        name: "Navigation Style",
        description: "Customize the style of the navigation bar",
        emoji: "navigation",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "foryou_layout",
        name: "For You Layout",
        description: "Change the app logo with presets or custom images",
        emoji: "home",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "tracks_layout",
        name: "Tracks Layout",
        description: "Change how the tracks are shown in the tracks page",
        emoji: "format-list-numbered",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "playlists_style",
        name: "Playlists Style",
        description: "Change how the playlists are shown",
        emoji: "list-alt",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "discover_layout",
        name: "Discover Layout",
        description: "Change how the discover page is shown",
        emoji: "auto-awesome",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "player_style",
        name: "Player Style",
        description: "Change how the player is shown",
        emoji: "music-note",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "fonts",
        name: "Fonts",
        description: "Change font related settings",
        emoji: "font-download",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "border_radius",
        name: "Border Radius",
        description: "Change the border radius of elements",
        emoji: "border-clear",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "animations",
        name: "Animations",
        description: "Change the animations while navigating",
        emoji: "animation",
        type: "action",
        defaultValue: null,
      },
    ],
  },
  app: {
    title: "Inami",
    settings: [
      {
        codename: "homescreen",
        name: "Homescreen",
        description: "Change how the app looks on the home screen",
        emoji: "logo-dev",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
};

export const CATEGORY_ICON_MAP: Record<string, string> = {
  options: "settings",
  themes: "palette",
  colors: "color-lens",
  views: "visibility",
  app: "apps",
};
